import { createFileRoute } from '@tanstack/react-router';
import { useMarketInsight, useGenerateMarketInsight } from '@/services/ai-analysis.queries';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { BrainCircuit, Info, AlertTriangle, TrendingUp, Sparkles, Loader2 } from 'lucide-react';
import { format } from 'date-fns';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

export const Route = createFileRoute('/egg-market-analysis')({
  head: () => ({
    meta: [
      { title: 'AI Egg Market Analysis | Daily Insights & Trends' },
      { name: 'description', content: 'Explore AI-powered analysis of the Indian egg market. Fact-based trends, movement analysis, and regional summaries.' }
    ]
  }),
  component: MarketAnalysisPage
});

function MarketAnalysisPage() {
  const { data: insight, isLoading } = useMarketInsight('daily_summary', 'national');
  const generate = useGenerateMarketInsight();

  const handleAnalyze = async () => {
    try {
      await generate.mutateAsync({ type: 'daily_summary', scope: 'national' });
      toast.success("AI analysis updated successfully!");
    } catch (error) {
      toast.error("Failed to generate AI analysis. Please check API configuration.");
    }
  };

  return (
    <div className="container py-8 space-y-8">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="flex flex-col gap-4">
          <div className="flex items-center gap-2 text-primary">
            <BrainCircuit className="w-5 h-5" />
            <span className="text-sm font-bold uppercase tracking-widest">AI Market Analysis</span>
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight">Today's Market Insights</h1>
          <p className="text-muted-foreground text-lg max-w-2xl">
            Fact-based, transparent analysis of verified egg rates across India, generated by our AI Market Data Engine.
          </p>
        </div>

        <Button 
          size="lg" 
          className="rounded-full shadow-lg shadow-primary/20 hover:shadow-primary/30 group"
          onClick={handleAnalyze}
          disabled={generate.isPending}
        >
          {generate.isPending ? (
            <Loader2 className="w-5 h-5 animate-spin mr-2" />
          ) : (
            <Sparkles className="w-5 h-5 mr-2 group-hover:animate-pulse" />
          )}
          Analyze Now
        </Button>
      </div>

      <div className="grid gap-8 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          {isLoading ? (
            <Card className="animate-pulse">
              <div className="h-64 bg-muted rounded-lg" />
            </Card>
          ) : insight ? (
            <Card className="overflow-hidden border-primary/20 bg-primary/[0.02]">
              <CardHeader className="border-b bg-primary/[0.03]">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-2xl">{insight.title}</CardTitle>
                  <Badge variant={insight.confidence === 'high' ? 'default' : 'secondary'}>
                    {insight.confidence.toUpperCase()} CONFIDENCE
                  </Badge>
                </div>
                <div className="text-xs text-muted-foreground mt-2 flex items-center gap-2">
                  <span>Analysis Date: {format(new Date(insight.analysisDate), 'PPP')}</span>
                  <span>•</span>
                  <span>Model: DeepSeek Optimized</span>
                </div>
              </CardHeader>
              <CardContent className="pt-6 prose prose-amber dark:prose-invert max-w-none">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{insight.content}</ReactMarkdown>
              </CardContent>
            </Card>
          ) : (
            <Card className="flex flex-col items-center justify-center py-20 text-center">
              <div className="w-12 h-12 bg-muted rounded-full flex items-center justify-center mb-4">
                <Info className="w-6 h-6 text-muted-foreground" />
              </div>
              <h3 className="text-lg font-semibold">No Analysis Available</h3>
              <p className="text-muted-foreground">The AI engine is currently processing today's market data.</p>
            </Card>
          )}

          <div className="bg-muted/30 border rounded-lg p-6 flex gap-4">
            <Info className="w-6 h-6 text-primary shrink-0" />
            <div className="text-sm space-y-2">
              <p className="font-semibold">AI Disclosure & Transparency</p>
              <p className="text-muted-foreground leading-relaxed">
                This market analysis is generated based on verified egg rate data from our database. It uses historical trends, price changes, and regional movements to provide context. AI never invents prices or market events. This should not be treated as a guaranteed price prediction or financial advice.
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <TrendingUp className="w-5 h-5" />
                Key Trends
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="p-4 rounded-lg bg-green-500/5 border border-green-500/10">
                <p className="text-xs font-bold text-green-600 uppercase mb-1">Weekly Outlook</p>
                <p className="text-sm font-medium">Positive momentum across 12 states.</p>
              </div>
              <div className="p-4 rounded-lg bg-amber-500/5 border border-amber-500/10">
                <p className="text-xs font-bold text-amber-600 uppercase mb-1">Regional Volatility</p>
                <p className="text-sm font-medium">High fluctuation detected in South India markets.</p>
              </div>
              <div className="p-4 rounded-lg bg-blue-500/5 border border-blue-500/10">
                <p className="text-xs font-bold text-blue-600 uppercase mb-1">Data Coverage</p>
                <p className="text-sm font-medium">98.4% of active markets verified today.</p>
              </div>
            </CardContent>
          </Card>

          <Card className="border-red-500/20 bg-red-500/5">
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2 text-red-600">
                <AlertTriangle className="w-5 h-5" />
                Data Integrity
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                All insights are linked to verified source IDs. In case of anomalies, the AI flags the result for manual review by our market analysts.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
