import { BrainCircuit, Info, ShieldCheck } from "lucide-react";
import { format } from "date-fns";
import ReactMarkdown from "react-markdown";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { MarketInsight } from "@/types/ai";
import { cn } from "@/lib/utils";

interface InsightViewProps {
  insight: MarketInsight;
  className?: string;
  showDisclosure?: boolean;
}

export function InsightView({ insight, className, showDisclosure = true }: InsightViewProps) {
  return (
    <div className={cn("space-y-6", className)}>
      <Card className="overflow-hidden border-primary/20 bg-primary/[0.02]">
        <CardHeader className="border-b bg-primary/[0.03] py-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
            <div className="space-y-1">
              <div className="flex items-center gap-2 text-primary">
                <BrainCircuit className="size-4" />
                <span className="text-[10px] font-bold uppercase tracking-widest">AI Market Analysis</span>
              </div>
              <CardTitle className="text-xl sm:text-2xl font-display">{insight.title}</CardTitle>
            </div>
            <Badge 
              variant="outline" 
              className={cn(
                "w-fit text-[10px] font-bold tracking-tighter",
                insight.confidence === 'high' ? "border-green-500/50 text-green-600 bg-green-50" : 
                insight.confidence === 'medium' ? "border-amber-500/50 text-amber-600 bg-amber-50" : 
                "border-red-500/50 text-red-600 bg-red-50"
              )}
            >
              {insight.confidence.toUpperCase()} CONFIDENCE
            </Badge>
          </div>
          <div className="flex items-center gap-3 mt-3 text-[10px] text-muted-foreground font-medium uppercase tracking-wider">
            <span className="flex items-center gap-1">
              <ShieldCheck className="size-3 text-success" />
              Verified Data Analysis
            </span>
            <span>•</span>
            <span>{format(new Date(insight.analysisDate), 'PPP')}</span>
          </div>
        </CardHeader>
        <CardContent className="pt-6 prose prose-sm sm:prose-base prose-amber dark:prose-invert max-w-none prose-p:leading-relaxed prose-headings:font-display">
          <ReactMarkdown>{insight.content}</ReactMarkdown>
        </CardContent>
      </Card>

      {showDisclosure && (
        <div className="bg-muted/30 border rounded-lg p-4 sm:p-5 flex gap-4">
          <Info className="size-5 text-primary shrink-0 mt-0.5" />
          <div className="text-xs sm:text-sm space-y-1.5">
            <p className="font-bold text-foreground">AI Disclosure & Transparency</p>
            <p className="text-muted-foreground leading-relaxed">
              This analysis is generated by our AI Market Data Engine using verified egg rates, historical trends, and regional movements. AI never invents prices or market events. All insights are traceable to database records. This is an information layer and should not be treated as financial advice or a guaranteed price prediction.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
