/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EggMarketAnalysisRouteImport } from './routes/egg-market-analysis'
import { Route as EggRateHistoryRouteImport } from './routes/egg-rate-history'
import { Route as EggRateTodayRouteImport } from './routes/egg-rate-today'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatesRouteImport } from './routes/states'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as ApiCronRouteImport } from './routes/api.cron'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as EggRateDateRouteImport } from './routes/egg-rate.$date'
import { Route as StateSlugRouteImport } from './routes/state.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminActivityLogsRouteImport } from './routes/_authenticated/admin/activity-logs'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin/ai'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminCitiesRouteImport } from './routes/_authenticated/admin/cities'
import { Route as AuthenticatedAdminConflictsRouteImport } from './routes/_authenticated/admin/conflicts'
import { Route as AuthenticatedAdminExportsRouteImport } from './routes/_authenticated/admin/exports'
import { Route as AuthenticatedAdminImportsRouteImport } from './routes/_authenticated/admin/imports'
import { Route as AuthenticatedAdminMarketsRouteImport } from './routes/_authenticated/admin/markets'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminQualityRouteImport } from './routes/_authenticated/admin/quality'
import { Route as AuthenticatedAdminRateHistoryRouteImport } from './routes/_authenticated/admin/rate-history'
import { Route as AuthenticatedAdminRatesRouteImport } from './routes/_authenticated/admin/rates'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin/seo'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSourcesRouteImport } from './routes/_authenticated/admin/sources'
import { Route as AuthenticatedAdminStatesRouteImport } from './routes/_authenticated/admin/states'
import { Route as AuthenticatedAdminSystemLogsRouteImport } from './routes/_authenticated/admin/system-logs'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as CitySlugEggRateHistoryRouteImport } from './routes/city.$slug.egg-rate-history'
import { Route as StateSlugEggRateHistoryRouteImport } from './routes/state.$slug.egg-rate-history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EggMarketAnalysisRoute = EggMarketAnalysisRouteImport.update({
  id: '/egg-market-analysis',
  path: '/egg-market-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const EggRateHistoryRoute = EggRateHistoryRouteImport.update({
  id: '/egg-rate-history',
  path: '/egg-rate-history',
  getParentRoute: () => rootRouteImport,
} as any)
const EggRateTodayRoute = EggRateTodayRouteImport.update({
  id: '/egg-rate-today',
  path: '/egg-rate-today',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EggRateDateRoute = EggRateDateRouteImport.update({
  id: '/egg-rate/$date',
  path: '/egg-rate/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const StateSlugRoute = StateSlugRouteImport.update({
  id: '/state/$slug',
  path: '/state/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminActivityLogsRoute =
  AuthenticatedAdminActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCitiesRoute =
  AuthenticatedAdminCitiesRouteImport.update({
    id: '/cities',
    path: '/cities',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConflictsRoute =
  AuthenticatedAdminConflictsRouteImport.update({
    id: '/conflicts',
    path: '/conflicts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExportsRoute =
  AuthenticatedAdminExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportsRoute =
  AuthenticatedAdminImportsRouteImport.update({
    id: '/imports',
    path: '/imports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMarketsRoute =
  AuthenticatedAdminMarketsRouteImport.update({
    id: '/markets',
    path: '/markets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminQualityRoute =
  AuthenticatedAdminQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRateHistoryRoute =
  AuthenticatedAdminRateHistoryRouteImport.update({
    id: '/rate-history',
    path: '/rate-history',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRatesRoute = AuthenticatedAdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSourcesRoute =
  AuthenticatedAdminSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStatesRoute =
  AuthenticatedAdminStatesRouteImport.update({
    id: '/states',
    path: '/states',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSystemLogsRoute =
  AuthenticatedAdminSystemLogsRouteImport.update({
    id: '/system-logs',
    path: '/system-logs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const CitySlugEggRateHistoryRoute = CitySlugEggRateHistoryRouteImport.update({
  id: '/egg-rate-history',
  path: '/egg-rate-history',
  getParentRoute: () => CitySlugRoute,
} as any)
const StateSlugEggRateHistoryRoute = StateSlugEggRateHistoryRouteImport.update({
  id: '/egg-rate-history',
  path: '/egg-rate-history',
  getParentRoute: () => StateSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/egg-market-analysis': typeof EggMarketAnalysisRoute
  '/egg-rate-history': typeof EggRateHistoryRoute
  '/egg-rate-today': typeof EggRateTodayRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api/cron': typeof ApiCronRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$slug': typeof CitySlugRouteWithChildren
  '/compare/$slug': typeof CompareSlugRoute
  '/egg-rate/$date': typeof EggRateDateRoute
  '/state/$slug': typeof StateSlugRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/conflicts': typeof AuthenticatedAdminConflictsRoute
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/admin/rate-history': typeof AuthenticatedAdminRateHistoryRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/states': typeof AuthenticatedAdminStatesRoute
  '/admin/system-logs': typeof AuthenticatedAdminSystemLogsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/city/$slug/egg-rate-history': typeof CitySlugEggRateHistoryRoute
  '/state/$slug/egg-rate-history': typeof StateSlugEggRateHistoryRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/egg-market-analysis': typeof EggMarketAnalysisRoute
  '/egg-rate-history': typeof EggRateHistoryRoute
  '/egg-rate-today': typeof EggRateTodayRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/api/cron': typeof ApiCronRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$slug': typeof CitySlugRouteWithChildren
  '/compare/$slug': typeof CompareSlugRoute
  '/egg-rate/$date': typeof EggRateDateRoute
  '/state/$slug': typeof StateSlugRouteWithChildren
  '/blog': typeof BlogIndexRoute
  '/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/conflicts': typeof AuthenticatedAdminConflictsRoute
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/admin/rate-history': typeof AuthenticatedAdminRateHistoryRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/states': typeof AuthenticatedAdminStatesRoute
  '/admin/system-logs': typeof AuthenticatedAdminSystemLogsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/city/$slug/egg-rate-history': typeof CitySlugEggRateHistoryRoute
  '/state/$slug/egg-rate-history': typeof StateSlugEggRateHistoryRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/egg-market-analysis': typeof EggMarketAnalysisRoute
  '/egg-rate-history': typeof EggRateHistoryRoute
  '/egg-rate-today': typeof EggRateTodayRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/api/cron': typeof ApiCronRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$slug': typeof CitySlugRouteWithChildren
  '/compare/$slug': typeof CompareSlugRoute
  '/egg-rate/$date': typeof EggRateDateRoute
  '/state/$slug': typeof StateSlugRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/activity-logs': typeof AuthenticatedAdminActivityLogsRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/_authenticated/admin/conflicts': typeof AuthenticatedAdminConflictsRoute
  '/_authenticated/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/_authenticated/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/_authenticated/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/_authenticated/admin/rate-history': typeof AuthenticatedAdminRateHistoryRoute
  '/_authenticated/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/_authenticated/admin/states': typeof AuthenticatedAdminStatesRoute
  '/_authenticated/admin/system-logs': typeof AuthenticatedAdminSystemLogsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/city/$slug/egg-rate-history': typeof CitySlugEggRateHistoryRoute
  '/state/$slug/egg-rate-history': typeof StateSlugEggRateHistoryRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cities'
    | '/contact'
    | '/disclaimer'
    | '/egg-market-analysis'
    | '/egg-rate-history'
    | '/egg-rate-today'
    | '/llms.txt'
    | '/offline'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/terms'
    | '/trends'
    | '/admin'
    | '/api/cron'
    | '/blog/$slug'
    | '/city/$slug'
    | '/compare/$slug'
    | '/egg-rate/$date'
    | '/state/$slug'
    | '/blog/'
    | '/admin/activity-logs'
    | '/admin/ai'
    | '/admin/announcements'
    | '/admin/cities'
    | '/admin/conflicts'
    | '/admin/exports'
    | '/admin/imports'
    | '/admin/markets'
    | '/admin/pages'
    | '/admin/quality'
    | '/admin/rate-history'
    | '/admin/rates'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/states'
    | '/admin/system-logs'
    | '/admin/users'
    | '/city/$slug/egg-rate-history'
    | '/state/$slug/egg-rate-history'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cities'
    | '/contact'
    | '/disclaimer'
    | '/egg-market-analysis'
    | '/egg-rate-history'
    | '/egg-rate-today'
    | '/llms.txt'
    | '/offline'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/terms'
    | '/trends'
    | '/api/cron'
    | '/blog/$slug'
    | '/city/$slug'
    | '/compare/$slug'
    | '/egg-rate/$date'
    | '/state/$slug'
    | '/blog'
    | '/admin/activity-logs'
    | '/admin/ai'
    | '/admin/announcements'
    | '/admin/cities'
    | '/admin/conflicts'
    | '/admin/exports'
    | '/admin/imports'
    | '/admin/markets'
    | '/admin/pages'
    | '/admin/quality'
    | '/admin/rate-history'
    | '/admin/rates'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/states'
    | '/admin/system-logs'
    | '/admin/users'
    | '/city/$slug/egg-rate-history'
    | '/state/$slug/egg-rate-history'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cities'
    | '/contact'
    | '/disclaimer'
    | '/egg-market-analysis'
    | '/egg-rate-history'
    | '/egg-rate-today'
    | '/llms.txt'
    | '/offline'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/terms'
    | '/trends'
    | '/_authenticated/admin'
    | '/api/cron'
    | '/blog/$slug'
    | '/city/$slug'
    | '/compare/$slug'
    | '/egg-rate/$date'
    | '/state/$slug'
    | '/blog/'
    | '/_authenticated/admin/activity-logs'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/cities'
    | '/_authenticated/admin/conflicts'
    | '/_authenticated/admin/exports'
    | '/_authenticated/admin/imports'
    | '/_authenticated/admin/markets'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/quality'
    | '/_authenticated/admin/rate-history'
    | '/_authenticated/admin/rates'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sources'
    | '/_authenticated/admin/states'
    | '/_authenticated/admin/system-logs'
    | '/_authenticated/admin/users'
    | '/city/$slug/egg-rate-history'
    | '/state/$slug/egg-rate-history'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CitiesRoute: typeof CitiesRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EggMarketAnalysisRoute: typeof EggMarketAnalysisRoute
  EggRateHistoryRoute: typeof EggRateHistoryRoute
  EggRateTodayRoute: typeof EggRateTodayRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatesRoute: typeof StatesRoute
  TermsRoute: typeof TermsRoute
  TrendsRoute: typeof TrendsRoute
  ApiCronRoute: typeof ApiCronRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CitySlugRoute: typeof CitySlugRouteWithChildren
  CompareSlugRoute: typeof CompareSlugRoute
  EggRateDateRoute: typeof EggRateDateRoute
  StateSlugRoute: typeof StateSlugRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egg-market-analysis': {
      id: '/egg-market-analysis'
      path: '/egg-market-analysis'
      fullPath: '/egg-market-analysis'
      preLoaderRoute: typeof EggMarketAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egg-rate-history': {
      id: '/egg-rate-history'
      path: '/egg-rate-history'
      fullPath: '/egg-rate-history'
      preLoaderRoute: typeof EggRateHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egg-rate-today': {
      id: '/egg-rate-today'
      path: '/egg-rate-today'
      fullPath: '/egg-rate-today'
      preLoaderRoute: typeof EggRateTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egg-rate/$date': {
      id: '/egg-rate/$date'
      path: '/egg-rate/$date'
      fullPath: '/egg-rate/$date'
      preLoaderRoute: typeof EggRateDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state/$slug': {
      id: '/state/$slug'
      path: '/state/$slug'
      fullPath: '/state/$slug'
      preLoaderRoute: typeof StateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/activity-logs': {
      id: '/_authenticated/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cities': {
      id: '/_authenticated/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AuthenticatedAdminCitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/conflicts': {
      id: '/_authenticated/admin/conflicts'
      path: '/conflicts'
      fullPath: '/admin/conflicts'
      preLoaderRoute: typeof AuthenticatedAdminConflictsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exports': {
      id: '/_authenticated/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AuthenticatedAdminExportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/imports': {
      id: '/_authenticated/admin/imports'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AuthenticatedAdminImportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/markets': {
      id: '/_authenticated/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AuthenticatedAdminMarketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quality': {
      id: '/_authenticated/admin/quality'
      path: '/quality'
      fullPath: '/admin/quality'
      preLoaderRoute: typeof AuthenticatedAdminQualityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rate-history': {
      id: '/_authenticated/admin/rate-history'
      path: '/rate-history'
      fullPath: '/admin/rate-history'
      preLoaderRoute: typeof AuthenticatedAdminRateHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rates': {
      id: '/_authenticated/admin/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AuthenticatedAdminRatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sources': {
      id: '/_authenticated/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AuthenticatedAdminSourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/states': {
      id: '/_authenticated/admin/states'
      path: '/states'
      fullPath: '/admin/states'
      preLoaderRoute: typeof AuthenticatedAdminStatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/system-logs': {
      id: '/_authenticated/admin/system-logs'
      path: '/system-logs'
      fullPath: '/admin/system-logs'
      preLoaderRoute: typeof AuthenticatedAdminSystemLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/city/$slug/egg-rate-history': {
      id: '/city/$slug/egg-rate-history'
      path: '/egg-rate-history'
      fullPath: '/city/$slug/egg-rate-history'
      preLoaderRoute: typeof CitySlugEggRateHistoryRouteImport
      parentRoute: typeof CitySlugRoute
    }
    '/state/$slug/egg-rate-history': {
      id: '/state/$slug/egg-rate-history'
      path: '/egg-rate-history'
      fullPath: '/state/$slug/egg-rate-history'
      preLoaderRoute: typeof StateSlugEggRateHistoryRouteImport
      parentRoute: typeof StateSlugRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminActivityLogsRoute: typeof AuthenticatedAdminActivityLogsRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminCitiesRoute: typeof AuthenticatedAdminCitiesRoute
  AuthenticatedAdminConflictsRoute: typeof AuthenticatedAdminConflictsRoute
  AuthenticatedAdminExportsRoute: typeof AuthenticatedAdminExportsRoute
  AuthenticatedAdminImportsRoute: typeof AuthenticatedAdminImportsRoute
  AuthenticatedAdminMarketsRoute: typeof AuthenticatedAdminMarketsRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminQualityRoute: typeof AuthenticatedAdminQualityRoute
  AuthenticatedAdminRateHistoryRoute: typeof AuthenticatedAdminRateHistoryRoute
  AuthenticatedAdminRatesRoute: typeof AuthenticatedAdminRatesRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSourcesRoute: typeof AuthenticatedAdminSourcesRoute
  AuthenticatedAdminStatesRoute: typeof AuthenticatedAdminStatesRoute
  AuthenticatedAdminSystemLogsRoute: typeof AuthenticatedAdminSystemLogsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminActivityLogsRoute: AuthenticatedAdminActivityLogsRoute,
    AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminCitiesRoute: AuthenticatedAdminCitiesRoute,
    AuthenticatedAdminConflictsRoute: AuthenticatedAdminConflictsRoute,
    AuthenticatedAdminExportsRoute: AuthenticatedAdminExportsRoute,
    AuthenticatedAdminImportsRoute: AuthenticatedAdminImportsRoute,
    AuthenticatedAdminMarketsRoute: AuthenticatedAdminMarketsRoute,
    AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
    AuthenticatedAdminQualityRoute: AuthenticatedAdminQualityRoute,
    AuthenticatedAdminRateHistoryRoute: AuthenticatedAdminRateHistoryRoute,
    AuthenticatedAdminRatesRoute: AuthenticatedAdminRatesRoute,
    AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
    AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSourcesRoute: AuthenticatedAdminSourcesRoute,
    AuthenticatedAdminStatesRoute: AuthenticatedAdminStatesRoute,
    AuthenticatedAdminSystemLogsRoute: AuthenticatedAdminSystemLogsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CitySlugRouteChildren {
  CitySlugEggRateHistoryRoute: typeof CitySlugEggRateHistoryRoute
}

const CitySlugRouteChildren: CitySlugRouteChildren = {
  CitySlugEggRateHistoryRoute: CitySlugEggRateHistoryRoute,
}

const CitySlugRouteWithChildren = CitySlugRoute._addFileChildren(
  CitySlugRouteChildren,
)

interface StateSlugRouteChildren {
  StateSlugEggRateHistoryRoute: typeof StateSlugEggRateHistoryRoute
}

const StateSlugRouteChildren: StateSlugRouteChildren = {
  StateSlugEggRateHistoryRoute: StateSlugEggRateHistoryRoute,
}

const StateSlugRouteWithChildren = StateSlugRoute._addFileChildren(
  StateSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CitiesRoute: CitiesRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EggMarketAnalysisRoute: EggMarketAnalysisRoute,
  EggRateHistoryRoute: EggRateHistoryRoute,
  EggRateTodayRoute: EggRateTodayRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatesRoute: StatesRoute,
  TermsRoute: TermsRoute,
  TrendsRoute: TrendsRoute,
  ApiCronRoute: ApiCronRoute,
  BlogSlugRoute: BlogSlugRoute,
  CitySlugRoute: CitySlugRouteWithChildren,
  CompareSlugRoute: CompareSlugRoute,
  EggRateDateRoute: EggRateDateRoute,
  StateSlugRoute: StateSlugRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
